# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: (cinder|jest.config.js)
JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: (cinder)
HTML_HTMLHINT_FILTER_REGEX_EXCLUDE: cinder
CSS_STYLELINT_FILTER_REGEX_EXCLUDE: cinder
PYTHON_PYLINT_FILTER_REGEX_EXCLUDE: cinder
