site_name: Secure Git Guide
site_url: "https://secure-git.guide/"
repo_url: "https://github.com/Nautilus-Cyberneering/secure-git-guide"
edit_uri: "https://github.com/Nautilus-Cyberneering/secure-git-guide/edit/main/docs"
site_description: "A collections of articles about Git, GitHub and GPG focused on security"
nav:
  - Home: index.md
theme:
  name: null
  custom_dir: "cinder"
