name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
